export const metadata = {
  title: "My Next App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <div className="page-content">
      <h1>Welcome to my next.js app!</h1>
    </div>
  );
}
